### ISSUE TITLE
investigate adding Content Blocker Extension

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot-ios#12]
migrate features from Onion Browser

**Comment by tladesignz** [comment]
So, I spent the whole day yesterday to create a facility to dynamically build A block- and HTTPS upgrade list.
Starting with the Chrome HSTS preload data for auto-upgrading to HTTPS.

Just to find out, when I turned to HTTPS Everywhere, that this seems to be a useless effort:

> You no longer need HTTPS Everyw[here](https://www.eff.org/https-everywhere/set-https-default-your-browser) to set HTTPS by default! Major browsers now offer native support for an HTTPS only mode. Find out how to turn it on here.
>
> This extension will be sunset by January 2023.

https://github.com/EFForg/https-everywhere

> Security and Privacy
>
> Continuing our dedication to privacy and security, Safari on iOS 15 and macOS Monterey supports automatic HTTPS upgrades and hides your IP address from known trackers. Automatic HTTPS upgrades are also supported in Safari 15 on older macOS versions.

https://webkit.org/blog/11989/new-webkit-features-in-safari-15/

> Safari on iOS 15 and macOS Monterey Automatically Upgrades Web Connections to HTTPS on Compatible Sites for Improved Security

https://www.macrumors.com/2021/06/08/safari-ios-15-macos-monterey-https-upgrades/

> Automatic HTTPS upgrade[[LINK]](https://nemecek.be/blog/111/wkwebview-improvements-in-ios-15#automatic-https-upgrade)
WKWebView will now automatically upgrade known hosts to HTTPS protocol for security reasons. There is also a configuration flag to disable this behavior in cases it causes problems in your app.

https://nemecek.be/blog/111/wkwebview-improvements-in-ios-15#automatic-https-upgrade

https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/3752243-upgradeknownhoststohttps

Now I'm investigating (ad-)block lists. In Onion Browser, this area was pretty under-maintained. There's a stone-old `urlblocker.json` file, where I have currently no idea where that came from and how to update it. :-/

**Comment by tladesignz** [comment]
Apparently, the list was hand-groomed by Joshua Stein:
https://github.com/jcs/endless/commit/c16aac10ac7cdb531c31716f51c17eb81f3a8aab

And I'm afraid, we can't even use it anymore:
https://github.com/jcs/endless/blob/master/LICENSE


Is CC BY-SA 3.0 good to be used in our iOS app licensed under MIT?
https://easylist.to/pages/about.html

**Comment by n8fr8** [comment]
Consider blocklists from Rethink https://rethinkdns.com/configure

**Comment by n8fr8** [comment]
- allow user to copy and paste in a list of domains to block
- allow user to choose to block font loading
- allow user to paste in custom regex?
- block all third-party scripts?

**Comment by n8fr8** [comment]
We are not going to bundle our own domain / path blocklist for now

**Comment by tladesignz** [comment]
Oh, you so get an absolutely crazy editor... Wait for the TestFlight!
