### ISSUE TITLE
explore using app-site-association and URL for orbot launch

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot-ios#16]
instead of custom URI scheme (which can be hijacked), we instead use https://orbot.app/start/foo URL to launch Orbot since we can authentication this with apple appsite association feature.

We can also add a page to the Orbot.app website to tell the user to install Orbot if they don't have it, which is a nice failover.

**Comment by tladesignz** [comment]
@n8fr8, where's the source for https://orbot.app?

**Comment by tladesignz** [comment]
Forget it, I found it: https://gitlab.com/guardianproject/orbot-app-website

**Comment by tladesignz** [comment]
Uupsi. Just recognized, I use https://orbot.app/rc/ instead of `/start/`. Good enough or should I change?
