### ISSUE TITLE
Bug: reenable the vpn doesn't work 

### ISSUE THREAD

**Issue by metemaddar** [guardianproject/orbot-ios#17]
On android 11, I've selected the apps to use orbot, whenever we disable vpn mode and we want to enable it again, it enposible till we disconnect and reconnect the tor,

It would be appreciated if you make an update for it.

**Comment by tladesignz** [comment]
Sorry, you're barking at the wrong tree - this is Orbot for **iOS**. 

I created an issue for you in the right one: https://github.com/guardianproject/orbot/issues/660

Please follow up there! Thank you!
