### ISSUE TITLE
Doesn't work on odysee

### ISSUE THREAD

**Issue by IronMaltese** [guardianproject/orbot-ios#21]
Odysee.com works on Desktop Tor Browser, but doesn't work on mobile, I've opened another issue here https://github.com/OdyseeTeam/odysee-frontend/issues/1052

**Comment by tladesignz** [comment]
I see an Cloudflare redirect. It seems, the page only works half-way.

Cloudflare has a special exemption for Tor Browser. It is identified via the "User-Agent" HTTP header.
You will need a browser where you can modify that header.

You can try [Onion Browser](http://onionbrowser.com) and set the Tor browser user agent header there. You can do you own or you can one of the predefined ones. Note, that Onion Browser currently doesn't work properly through Orbot. You will need to switch that off.
