### ISSUE TITLE
Add support for updated Moat!

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot-ios#23]
New capabilities added for region specific bridges

https://gitlab.torproject.org/meskio/rdsys/-/blob/doc_moat_api/doc/moat.md

**Comment by n8fr8** [comment]
Python implementation of the Censorship API routes https://github.com/onionshare/onionshare/blob/a998a327af831caf9dbfa13d232bd874071a81d5/cli/onionshare_cli/censorship.py

**Comment by tladesignz** [comment]
There it is for all apps to use: 
https://github.com/tladesignz/IPtProxyUI-ios/commit/205d31c66510d4a2566c29aebe432e2448213419
