### ISSUE TITLE
Orbot doesn’t connect - shows connecting and then back to disconnected

### ISSUE THREAD

**Issue by ericswpark** [guardianproject/orbot-ios#24]
As per title, Orbot suddenly stopped working on my iPhone. When I press the connect button, the app shows that it is connecting for about fifteen seconds before changing back to the “disconnected” button. 

Here is the log:

```
Jun 01 09:21:05.000 [notice] Tor 0.4.6.10 opening new log file.
Jun 01 09:21:05.274 [notice] We compiled with OpenSSL 101010df: OpenSSL 1.1.1m  14 Dec 2021 and we are running with OpenSSL 101010df: 1.1.1m. These two versions should be binary compatible.
Jun 01 09:21:05.284 [notice] Tor 0.4.6.10 running on Darwin with Libevent 2.1.12-stable, OpenSSL 1.1.1m, Zlib 1.2.11, Liblzma 5.2.5, Libzstd N/A and Unknown N/A as libc.
Jun 01 09:21:05.284 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jun 01 09:21:05.284 [notice] Configuration file "/private/var/mobile/Containers/Data/PluginKitPlugin/6DD9EC68-75BF-4411-B0F1-4C14AC096B88/.torrc" not present, using reasonable defaults.
Jun 01 09:21:05.288 [warn] MaxMemInQueues is set to a low value; if your client doesn't work, this may be the reason why.
Jun 01 09:21:05.292 [notice] Opening Socks listener on 127.0.0.1:0
Jun 01 09:21:05.292 [notice] Socks listener listening on port 56782.
Jun 01 09:21:05.293 [notice] Opened Socks listener connection (ready) on 127.0.0.1:56782
Jun 01 09:21:05.293 [notice] Opening DNS listener on 127.0.0.1:0
Jun 01 09:21:05.293 [notice] DNS listener listening on port 63092.
Jun 01 09:21:05.293 [notice] Opened DNS listener connection (ready) on 127.0.0.1:63092
Jun 01 09:21:05.293 [notice] Opening Control listener on 127.0.0.1:0
Jun 01 09:21:05.293 [notice] Control listener listening on port 56783.
Jun 01 09:21:05.293 [notice] Opened Control listener connection (ready) on 127.0.0.1:56783
Jun 01 09:21:05.000 [notice] {GENERAL} Parsing GEOIP IPv4 file /var/containers/Bundle/Application/5D84940D-1C99-4E40-9639-2FD6E4A06AF7/Orbot.app/Frameworks/Tor.framework/GeoIP.bundle/geoip.
Jun 01 09:21:05.000 [notice] {GENERAL} Parsing GEOIP IPv6 file /var/containers/Bundle/Application/5D84940D-1C99-4E40-9639-2FD6E4A06AF7/Orbot.app/Frameworks/Tor.framework/GeoIP.bundle/geoip6.
Jun 01 09:21:05.000 [notice] {CONTROL} Bootstrapped 0% (starting): Starting
```

It worked fine a couple weeks back when the app was initially out but since then I’ve been unable to get it working. I’m unsure whether this was before or after the update to iOS 15.5. 

Currently using an iPhone XS Max running iOS 15.5 (19F77). Orbot is on version 1.2.0 build 10.

None of the settings have been changed on Orbot. I’ve tried force-closing and restarting the app. I’ve also tried deleting the VPN configuration in iOS settings and re-installing the VPN configuration.

I don’t use bridges. (But I have tried connecting with all the bridge types, which didn’t help fix the issue.)

**Comment by ericswpark** [comment]
@tladesignz thanks for the reply.

> Can you tell where you're situated? Usually, I see this kind of behaviour when Tor has trouble connecting because it gets blocked, resp. parts of the Internet get blocked so it cannot find servers.

I'm currently situated in South Korea. There are no problems with Tor connectivity here.

> Did you play with the node settings? That could be another reason. You might have set something which limited you to e.g. one entry node, which now is gone.

No settings have been modified. The fields for the node settings are all blank.

> If nothing helps, you could try remove the app and reinstall.

That worked for some reason, thanks!

> Could you share the log when trying bridges? Or does that look exactly the same?

Pretty much the same if I remember correctly; it also stops with the following line at the end:

```
{CONTROL} Bootstrapped 0% (starting): Starting
```

Since I cannot reproduce the issue anymore after re-installing, I'll close the issue now. Will re-open in the future if it happens again. Thanks!

**Comment by tladesignz** [comment]
Thank you for the feedback. I have to say: I'm stumped. No idea what could cause this. Maybe Tor can manoeuvre itself in a situation where it breaks its cached circuit "microdescriptors" configuration in a way, that it can't start again or something similar?

I'll keep an eye out for it. Maybe this happens to me sometimes. Or maybe it is gone with the new version.

However, on a quick scan since version 0.4.6.10, I couldn't find anything related:
https://gitlab.torproject.org/tpo/core/tor/-/raw/release-0.4.7/ReleaseNotes

**Comment by ericswpark** [comment]
I’ve tried all the bridge options (including requesting one from Tor Project), quit and restarted the app, removed and re-added the VPN configuration from iOS settings, and tried starting the VPN with the switch in iOS settings rather than using the Orbot on button. All of them fail with the logs matching above.

The only thing I haven’t tried is reinstall the app, because I’m pretty sure that will fix it, but then I won’t be able to reproduce the issue until it occurs again and it’s rather cumbersome to reinstall every time this problem occurs.

**Comment by HenriquePoltergeist** [comment]
On Android there seems to be a similar thing. 
Orbot is connected but has no data exchange or the viewer does not correctly display the amount of transmissions. There also seems to be Snowflake routing disabling on its own sometimes.
 
Suggestion: also send logs manually, as in Waze and Netmonster and that the exchange of data is also accounted for when we help another user on Snowflake.

**Comment by ericswpark** [comment]
@tladesignz is that what the problem is, the Orbot app (or some sort of extension within it) running out of memory and quitting early?

Two things I can think of: maybe a memory “usage” screen that shows currently used memory so that users can tell why the problem is occurring, as well as an entry in the log if the app (and/or the extension) was killed by the iOS system because it hit against the memory limit? Also the reset cache button you mentioned sounds great as well. But the first two will at least let users figure out what is going wrong instead of just silently dying.

I’ve had the app kill the connection in the background – I noticed the VPN indicator did not show anymore and when I came back to the app it was disabled. Could be very dangerous for some users where Tor needs to stay on for privacy reasons.

**Comment by tladesignz** [comment]
> @tladesignz is that what the problem is, the Orbot app (or some sort of extension within it) running out of memory and quitting early?

The "Network Extension", which contains Tor running in the background.

It's just a shot in the dark.

> Two things I can think of: maybe a memory “usage” screen that shows currently used memory so that users can tell why the problem is occurring, as well as an entry in the log if the app (and/or the extension) was killed by the iOS system because it hit against the memory limit? Also the reset cache button you mentioned sounds great as well. But the first two will at least let users figure out what is going wrong instead of just silently dying.

Yeah, would be nice to have, but we can't measure that. iOS security restrictions.

> I’ve had the app kill the connection in the background – I noticed the VPN indicator did not show anymore and when I came back to the app it was disabled. Could be very dangerous for some users where Tor needs to stay on for privacy reasons.

Yes, unfortunately Network Extensions fail open and we can't do much about it automatically.

There is a flag in Settings -> VPN -> Orbot -> Connect on demand

Check that, on the Extension will be restarted automatically.

Not found a way to provide that from within the app and/or automatically set it. 🤷 Sorry.

**Comment by tladesignz** [comment]
I added that "clear cache" button I was thinking about, and I also revisited the whole "connect on demand" thing. I actually recognized, that thinking this would be beyond our control was actually an old memory which wasn't completely informed.

I was able to leverage it and create a "reconnect on error" feature. Which uses the "connect on demand" feature of the system but disables that again automatically, after the user purposefully stopped Tor again. Seems way more useful this way, and definitely easier to discover for unwitting users.

I hope this will help your situation. I'll close this for now. Please join the TestFlight, if you need this soon: https://orbot.app/download

**Comment by meglio** [comment]
![image](https://github.com/guardianproject/orbot-apple/assets/282177/42464ac7-c559-4a57-8d90-675e5c91cfd2)

Fails to connect.
Bridges I’m using are the ones from the telegeam bot.
Connect on Demand is ON.
The connection percentage goes up to ~60-70% and  then stops and disconnects. So at the end of the day I have made zero successful connections.

nothing helps. Please advise.

location: Australia
