### ISSUE TITLE
support vmess protocol？

### ISSUE THREAD

**Issue by CNKCQ** [guardianproject/orbot-ios#27]
Our service is based on v2ray

**Comment by tladesignz** [comment]
Sorry, but my knowledge of V2Ray/VMess is very limited. I know that it exists, but I never dived into it. Most docs seem to be in Chinese. That doesn't help. So please forgive my ignorance.

Tor itself is based around TCP. If V2Ray/VMess tunnels over that, Tor, resp. Orbot should be transparent to it.

If it needs UDP, than there's a chance to have support in the future. I hear people at Tor talk and think about how to support UDP.

If VMess is at the same level as TCP/UDP, then, I'm afraid, we will never be able to support it. It is highly unlikely that Tor Project will ever consider to support that.
