### ISSUE TITLE
Orbot Intel Mac

### ISSUE THREAD

**Issue by MacFullTime** [guardianproject/orbot-ios#29]
Hello!

Thanks for the astonishing work, I am currently using your app on my iPhone and it works extremely well!
Which leads me to the question whether it would perhaps be possible to also make this app available on Intel Macs? Many people are still using these, and having Orbot to thwart censorship in some countries would be really beneficial.

Yours faithfully

**Comment by tladesignz** [comment]
Thank you for your feedback which undermines the case for the work I recently started:

c9665cfd954c217ddba64db854b870d972f06362

Will still take a while until release and even longer for feature parity!

**Comment by MacFullTime** [comment]
That's great! Thank you very much.

**Comment by n8fr8** [comment]
> Thank you for your feedback which undermines the case for the work I recently started:

Did you mean undermines as in bad or good?

**Comment by tladesignz** [comment]
> > Thank you for your feedback which undermines the case for the work I recently started:
> 
> Did you mean undermines as in bad or good?

Uuups. Did I use that term wrong? I rather meant *underscore* or *emphasize*. :-)
