### ISSUE TITLE
AppPrivacyReport shouldn't be aware of network activities

### ISSUE THREAD

**Issue by edsburke** [guardianproject/orbot-ios#30]
# Problem
App Privacy Report of iOS can record all network activities even if Orbot VPN is in use, however, this should not take place for the sake of privacy.

Note that, [App Privacy Report](https://support.apple.com/en-us/HT212958) is a new feature since iOS 15.2.

# More details such as
## Related Work
are posted to the upstream work at https://github.com/eycorsican/leaf/issues/302

# Upvote Request
Hey Orbot community, please kindly help comment and / or upvote the upstream proposal https://github.com/eycorsican/leaf/issues/302 at Leaf community to better address this privacy issue.

**Comment by tladesignz** [comment]
See my comment in the linked issue: https://github.com/eycorsican/leaf/issues/302#issuecomment-1262201831

**Comment by tladesignz** [comment]
Closing this issue.
See arguments here: https://github.com/eycorsican/leaf/issues/302#issuecomment-1274276128
