### ISSUE TITLE
VPN periodically disconnecting on iPhone SE 2nd gen.

### ISSUE THREAD

**Issue by okpersonvern** [guardianproject/orbot-ios#5]
**Issue description:**
On an iPhone SE 2nd gen. Orbot's VPN connection will sometimes automatically disconnect, without user interaction.
OS: iOS 15.3.1 
Orbot version: 1.1.0 (6) from Testflight

**Steps to reproduce:**
1. Install Orbot from an iPhone SE 2nd gen. with the latest iOS version
2. Connect to Tor with Orbot
3. Leave Orbot's VPN connection turned on and let the device stay idle for a while
4. Wake the device and observe that the VPN disconnected

Extract from log at the time when issue last occured:

```
Mar 03 12:52:05.000 [notice] {GENERAL} Your system clock just jumped 281 seconds forward; assuming established circuits no longer work.
Mar 03 12:52:19.000 [warn] {CONFIG} MaxMemInQueues is set to a low value; if your client doesn't work, this may be the reason why.
Mar 03 12:52:19.000 [notice] Tor 0.4.6.9 opening log file.
Mar 03 12:52:19.000 [notice] {GENERAL} Received reload signal (hup). Reloading config and resetting internal state.
Mar 03 12:52:19.000 [notice] {CONFIG} Configuration file "/private/var/mobile/Containers/Data/PluginKitPlugin/72B35562-3C91-4F1C-B10E-4A2BEB826B38/.torrc" not present, using reasonable defaults.
Mar 03 12:52:19.000 [warn] {CONFIG} MaxMemInQueues is set to a low value; if your client doesn't work, this may be the reason why.
Mar 03 12:52:19.000 [notice] Tor 0.4.6.9 opening log file.
```

**Comment by okpersonvern** [comment]
Weirdly, it has not occurred again since I made this report. And yes the problem occured in that timeframe, but unfortunately I did not have a chance to copy the rest of the log before it was cleared.

I did not know about the connect on demand feature. Will be using that going forward!

**Comment by tladesignz** [comment]
> Weirdly, it has not occurred again since I made this report. And yes the problem occured in that timeframe, but unfortunately I did not have a chance to copy the rest of the log before it was cleared.

Too bad. Bad thanks for reporting anyway. I'll keep an eye out for something like this happening. But my experience yesterday was quite the opposite: I let it run and then forgot about it at all until a streaming app reminded me, that I seemed to be using a VPN. So it was *very* stable. Much more than I suspected.

But maybe what happened here is an adjustment of the system clock through SNTP which irritated Tor. 
(As it tells in the first line.)
But it should have restarted as it said in wanted to. There was nothing happening afterwards in the log?

> I did not know about the connect on demand feature. Will be using that going forward!

 👍

**Comment by okpersonvern** [comment]
No, those were the last lines in the log.

I do switch between wi-fi and mobile data many times a day. Not sure if that could trigger this. Conclusion for me is that steps to reproduce are uncertain, and probably unrelated to the time screen is idle. Will make a new comment with log if it occurs again.

**Comment by okpersonvern** [comment]
Hello. This occured 3 times during the weekend. I'm still not sure what triggers it. I did use mobile data a lot this weekend, and I know that I was using mobile data when the first disconnect occured (I don't remember what I did when the two other disconnects occured). But this could be wrong. 

I'm attaching full logs copied immediately after I discovered the disconnect (after turning on the screen). They are long.

[orbot-ios-disconnect1.txt](https://github.com/guardianproject/orbot-ios/files/8197711/orbot-ios-disconnect1.txt)
[orbot-ios-disconnect2.txt](https://github.com/guardianproject/orbot-ios/files/8197713/orbot-ios-disconnect2.txt)
[orbot-ios-disconnect3.txt](https://github.com/guardianproject/orbot-ios/files/8197714/orbot-ios-disconnect3.txt)

Next I will test whether the same issue occurs with a VPN provider's app with the connect on demand feature turned off. If it does, it is Apple that must be blamed.

**Comment by tladesignz** [comment]
Hmmm. Tor seems unable to find bridges after a device sleep.
Can you disclose your circumstances? Esp. your country and ISPs used.

Did you try using bridges? Does that improve the situation?

Are you in battery saving mode? If so, you might want to fully charge your device and switch off the battery saving mode.

**Comment by hellojaccc** [comment]
i had same experience, se 2nd gen. ios 15. low power mode.

after i woke up, there wasnt vpn icon in status bar.

**Comment by hellojaccc** [comment]
i think it need to send some keepalive packet

**Comment by okpersonvern** [comment]
> Hmmm. Tor seems unable to create circuits after a device sleep. Can you disclose your circumstances? Esp. your country and ISPs used.
> 
> Did you try using bridges? Does that improve the situation?
> 
> Are you in battery saving mode? If so, you might want to fully charge your device and switch off the battery saving mode.

Country: Norway. ISP: Telenor. After several tests, I am confident that my domestic internet is not blocking or throttling Tor in any way. For mobile traffic, it seems possible that Tor is being throttled, as using a bridge (one of my own) will sometimes result in better speeds. But it's hard to determine consistently.

I only use low power mode when battery is below 15%, and I'm pretty sure this isn't the cause of my issue.

I think this occurs when signal is poor. I had the VPN disconnect when I was connected to a wi-fi network, moving too far away from the router so the signal almost dropped. Occured while connected to a bridge. Full log from when disconnect happened is attached
[Orbot-ios disconnect wifi poor signal.txt](https://github.com/guardianproject/orbot-ios/files/8263760/Orbot-ios.disconnect.wifi.poor.signal.txt)
.

**Comment by okpersonvern** [comment]
But as this issue does not occur when 'connect on demand' is turned on, not sure how much of an issue it is. Perhaps 'connect on demand' can be turned on by default? Just a thought. There are probably pros and cons to that.
