### ISSUE TITLE
Strip unwanted leaf features

### ISSUE THREAD

**Issue by eycorsican** [guardianproject/orbot-ios#6]
The [default feature set](https://github.com/eycorsican/leaf/blob/ba17b0ad08a6755b75231b4efa08c66ea7540c39/leaf/Cargo.toml#L17) included in leaf contains a lot features, e.g. SSL, crypto, QUIC, Websocket, that have no use in this project. According to the config template, the minimal feature set could look like,
```toml
default = [
    "leaf/config-conf",
    "leaf/inbound-tun",
    "leaf/inbound-socks",
    "leaf/outbound-socks",
    "leaf/outbound-redirect",
    "leaf/outbound-direct",
    "leaf/outbound-drop"
]
```
This gives a much smaller binary.

It may need our own `leaf-ffi-orbot` library for doing so, just as [how `leaf-ffi` does](https://github.com/eycorsican/leaf/blob/master/leaf-ffi/Cargo.toml).

**Comment by tladesignz** [comment]
@eycorsican, *thank you so much* for your input!

@bitmold, have a look at my changes!

In a quick experiment, I could reduce libleaf.a for aarch64-apple-ios from 43.2 MB to 25.9 MB!
