### ISSUE TITLE
accessibility issues for blind user

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot-ios#7]
from a user email:

"I am a totally blind user and first want to thank you for your work. I am extremely happy that Orbotis now on iOS, but there needs to be an update for accessibility with voiceover, built in iOS screen reader for people visually impaired.

Absolutely everything seems to be functional, but all of the buttons are unlabeled. Log needs to be “log”, bridges should be  “bridges”, etc. apart from this, everything seems to work flawlessly. I have checked and clicked on all of the available buttons and seems to check out.

Apart from the above bug which needs to be fixed I would also like to add a suggestion. It would be nice if there were a setting to include or exclude countries that you connect to for a node similar to how you can configure on desktop."

**Comment by tladesignz** [comment]
Ok, so I played around with VoiceOver and improved button labels and marked some items which work as buttons as such. Also in `IPtProxyUI`, so this work also improves Onion Browser and others.

Too sad, that we don't this user here for direct feedback.

@n8fr8, do you want me to add the requested feature? I added #8. Please let me know there, if I should stop.
