### ISSUE TITLE
You might be able to further whittle down leaf binaries 

### ISSUE THREAD

**Issue by bitmold** [guardianproject/orbot-ios#9]
https://github.com/guardianproject/orbot/issues/625#issuecomment-1061639272

On this Orbot android leaf thread eycorsican says that using `leaf/config-json` instead of `leaf/config-conf` drops a bulky regex package and gives you an even smaller binary. 

I still haven't gotten a chance to return to leaf on Android myself, but if this is something you can do for iOS I'm sure it'd go a long way!

**Comment by tladesignz** [comment]
> It can be further reduced to 8.4MB by using leaf/config-json instead of leaf/config-conf because the conf format brings in a big dependency regex which is much bigger compares to a json parser. However the tun-fd option is missing in the json config as I never mind using this format for client applications.

I need the tun-fd option for iOS and the conf file format per se. Leaf is heavily underdocumented and the JSON config confuses me even more.
